# Generated by Django 3.0.5 on 2020-04-23 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0002_remove_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
